# VaultChatFormatter Configuration
#
# To reload this configuration file, run `/vaultchatformatter reload`.
# (and make sure you have the 'vaultchatformatter.reload' permission)

# The chat format.
#
# The following placeholders can be used in the format, and will be replaced
# by their corresponding value when the format is applied.
#
# {prefix} ==> the players prefix
# {suffix} ==> the players suffix
# {name} ==> the players name
#
# format codes: https://docs.advntr.dev/minimessage/format.html#color
format: "<{prefix}{name}{suffix}> "
