name: VaultChatFormatter
version: '${version}'
main: me.lucko.chatformatter.ChatFormatterPlugin
description: VaultChatFormatter is a plugin which formats the chat. wow
api-version: '1.21.11'

dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
      join-classpath: true
